name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  geolocator: ^13.0.4
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# dependency_overrides:
#   material_color_utilities: ^0.12.0
#   vector_math: ^2.1.5
#   async: ^2.13.0
#   fake_async: ^1.3.2
#   leak_tracker: ^11.0.1
#   leak_tracker_flutter_testing: ^3.0.10
#   leak_tracker_testing: ^3.0.2
#   flutter_lints: ^6.0.0
#   vm_service: ^15.0.0