// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK-pQ_v0jLfZhLHmy983jW5-48lUBcJxk',
    appId: '1:199558492048:web:ba8a7c305a245f90b78d15',
    messagingSenderId: '199558492048',
    projectId: 'attraction-memories',
    authDomain: 'attraction-memories.firebaseapp.com',
    databaseURL: 'https://attraction-memories-default-rtdb.firebaseio.com',
    storageBucket: 'attraction-memories.firebasestorage.app',
    measurementId: 'G-Z050SS5FB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SVEqBYyohr3QgB6lpp5NEP8sARglARw',
    appId: '1:199558492048:android:419e1d3886609d27b78d15',
    messagingSenderId: '199558492048',
    projectId: 'attraction-memories',
    databaseURL: 'https://attraction-memories-default-rtdb.firebaseio.com',
    storageBucket: 'attraction-memories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexSlOJwaL7Bgo_g2_a45dVrX_lPNrzJs',
    appId: '1:199558492048:ios:eb78bd0d8b16913db78d15',
    messagingSenderId: '199558492048',
    projectId: 'attraction-memories',
    databaseURL: 'https://attraction-memories-default-rtdb.firebaseio.com',
    storageBucket: 'attraction-memories.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexSlOJwaL7Bgo_g2_a45dVrX_lPNrzJs',
    appId: '1:199558492048:ios:eb78bd0d8b16913db78d15',
    messagingSenderId: '199558492048',
    projectId: 'attraction-memories',
    databaseURL: 'https://attraction-memories-default-rtdb.firebaseio.com',
    storageBucket: 'attraction-memories.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK-pQ_v0jLfZhLHmy983jW5-48lUBcJxk',
    appId: '1:199558492048:web:03b313d1d8f6f325b78d15',
    messagingSenderId: '199558492048',
    projectId: 'attraction-memories',
    authDomain: 'attraction-memories.firebaseapp.com',
    databaseURL: 'https://attraction-memories-default-rtdb.firebaseio.com',
    storageBucket: 'attraction-memories.firebasestorage.app',
    measurementId: 'G-3HDC4478G0',
  );
}
